apiVersion: v1
kind: ConfigMap
metadata:
  name: config-application-yml
data:
  application.yml: |
    hedera:
      mirror:
        grpc:
          listener:
            type: SHARED_POLL
        importer:
          startDate: 1970-01-01T00:00:00.000Z
          parser:
            record:
              entity:
                redis:
                  enabled: false
              sidecar:
                enabled: true
          downloader:
            accessKey: minioadmin
            cloudProvider: S3
            secretKey: minioadmin
            bucketName: hedera-streams
            endpointOverride: http://minio-0.minio.default.svc.cluster.local:9000
          initialAddressBook: /usr/etc/hedera-mirror-importer/local-dev-1-node.addressbook.f102.json.bin
          network: OTHER
        monitor:
          mirrorNode:
            grpc:
              host: mirror-node-grpc.default.svc.cluster.local
              port: 5600
            rest:
              host: mirror-node-rest.default.svc.cluster.local
              port: 5551
          publish:
            scenarios:
              pinger:
                properties:
                  amount: 1
                  maxTransactionFee: 10000
                  senderAccountId: 0.0.2
                  recipientAccountId: 0.0.55
                  transferTypes:
                    - CRYPTO
                receiptPercent: 1
                tps: 10
                type: CRYPTO_TRANSFER
          subscribe:
            grpc:
              hcs:
                enabled: false
            rest:
              transactionId:
                enabled: true
                samplePercent: 1
          network: OTHER
          nodes:
            - accountId: 0.0.3
              host: network-node.default.svc.cluster.local
          operator:
            accountId: 0.0.2
            privateKey: 302e020100300506032b65700422042091132178e72057a1d7528025956fe39b0b847f200ab59b2fdd367017f3087137