apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - name: port9000
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: port9001
      protocol: TCP
      port: 9001
      targetPort: 9001
  type: ClusterIP