apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv
spec:
  capacity:
    storage: 10Gi  
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/hedera-local-node/volumes/mirror-node-postgres/_data

