apiVersion: v1
kind: Service
metadata:
  name: mirror-node-rest
spec:
  selector:
    app: mirror-node-rest
  ports:
  - name: port5551
    protocol: TCP
    port: 5551
    nodePort: 31051
  type: NodePort
