apiVersion: v1
kind: Service
metadata:
  name: hedera-explorer
spec:
  selector:
    app: hedera-explorer
  ports:
    - name: port8080
      protocol: TCP
      port: 8080  
      targetPort: 8080  
      nodePort: 31080
  type: NodePort 