apiVersion: v1
kind: Service
metadata:
  name: envoy
spec:
  selector:
    app: envoy
  ports:
    - name: port50213
      protocol: TCP
      port: 50213  
      targetPort: 50213  
  type: ClusterIP 