apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-data-pv 
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/hedera-local-node/volumes/prometheus-data/_data