apiVersion: v1
kind: PersistentVolume
metadata:
  name: record-sidecar-uploader-pv-01
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/hedera-local-node/network-logs/node/recordStreams/record0.0.4/sidecar
